version: '3.8'

services:
  db_sorter:
    container_name: db_sorter_dev
    image: postgres:13-alpine
    volumes:
      - postgres_sorter_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    env_file:
      - ./.env.dev
    ports:
      - "5435:5432"

  web_sorter:
    container_name: web_soccer_sorter_dev
    image: web_soccer_sorter_dev_img
    build: .
    tty: true
    volumes:
      - .:/soccer_sorter
    ports:
      - 8000:8000
    depends_on:
      - db_sorter
    
    env_file:
      - ./.env.dev
    
volumes:
  postgres_sorter_data:
    
